import { library } from "@fortawesome/fontawesome-svg-core";

import {
  faCog,
  faMagnifyingGlass,
  faWallet,
  faCircleExclamation,
  faCalendar,
  faClock,
  faScroll,
  faSyncAlt,
  faGift,
  faEllipsisH,
  faHeart,
  faTrophy,
  faAdd,
  faClose,
  faUser,
  faSmile,
  faPaperPlane,
  faChevronDown,
  faChevronUp,
  faPowerOff,
  faArrowUp,
  faArrowDown,
  faTimes,
  faEyeSlash,
  faCircleCheck,
  faTrashAlt,
  faClockRotateLeft,
  faCogs,
} from "@fortawesome/free-solid-svg-icons";

const configure = () => {
  library.add(
    faCalendar,
    faClock,
    faCog,
    faEllipsisH,
    faGift,
    faHeart,
    faMagnifyingGlass,
    faScroll,
    faSyncAlt,
    faTrophy,
    faWallet,
    faGift,
    faEllipsisH,
    faAdd,
    faClose,
    faUser,
    faSmile,
    faPaperPlane,
    faCircleExclamation,
    faChevronDown,
    faChevronUp,
    faPowerOff,
    faArrowUp,
    faArrowDown,
    faTimes,
    faEyeSlash,
    faCircleCheck,
    faTrashAlt,
    faClockRotateLeft,
    faCogs
  );
};

export default { configure };
